name: Daily Health Tracker Pipeline

on:
  schedule:
    - cron: '30 1 * * *'  # Roda todo dia às 09h BRT (12h UTC)
  workflow_dispatch:      # Permite rodar manualmente

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Criar arquivo de credenciais do Google
        run: |
          echo "$GSCREDENTIALS" > gscredentials.json
        env:
          GSCREDENTIALS: ${{ secrets.GSCREDENTIALS }}

      - name: Rodar pipeline
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL}}
          FAT_SECRET_CONSUMER_KEY: ${{ secrets.FAT_SECRET_CONSUMER_KEY }}
          FATSECRET_CLIENT_SECRET: ${{ secrets.FAT_SECRET_CONSUMER_SECRET }}
          FATSECRET_CLIENT_ID: ${{ secrets.FAT_SECRET_CLIENT_ID }}
          FAT_SECRET_OAUTH_TOKEN: ${{ secrets.FAT_SECRET_OAUTH_TOKEN }}
          FAT_SECRET_OAUTH_SECRET: ${{ secrets.FAT_SECRET_OAUTH_SECRET }}

        run: |
          python -m src.main

